/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fedex.school.tcpserver;

/**
 *
 * @author fedex
 */
public class GUI extends javax.swing.JFrame {

    TCPSocket_server server;
    /**
     * Creates new form GUI
     * @param server
     */
    public GUI(TCPSocket_server server) {
        initComponents();
        this.server = server;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avviaBtn = new javax.swing.JButton();
        statuslbl = new javax.swing.JLabel();
        clientlbl = new javax.swing.JLabel();
        outputlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        avviaBtn.setText("Avvia Server");
        avviaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avviaBtnActionPerformed(evt);
            }
        });

        statuslbl.setText("SERVER OFFLINE");

        clientlbl.setText("                        ");

        outputlbl.setText("                            ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 272, Short.MAX_VALUE)
                        .addComponent(avviaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statuslbl)
                            .addComponent(clientlbl)
                            .addComponent(outputlbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statuslbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(avviaBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avviaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avviaBtnActionPerformed
        new Thread() {
            @Override
            public void run() {
                server.avviaServer();
            }
        }.start();
    }//GEN-LAST:event_avviaBtnActionPerformed
    
    public void setServerStatus(String status) {
        statuslbl.setText(status);
    }
    
    public void setClientStatus(String status) {
        clientlbl.setText(status);
    }
    
    public void setOutputStatus(String status) {
        outputlbl.setText(status);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avviaBtn;
    private javax.swing.JLabel clientlbl;
    private javax.swing.JLabel outputlbl;
    private javax.swing.JLabel statuslbl;
    // End of variables declaration//GEN-END:variables
}
