package com.fedex.tcpserver;

import java.awt.*;
import java.awt.event.*;
import java.net.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author fedex
 */
public class GUI extends javax.swing.JFrame {

    TCPSocket_server server;
    InetAddress client;
    GUI gui;
    
    /**
     * Creates new form GUI
     * @param server
     */
    public GUI(TCPSocket_server server) {
        initComponents();
        this.server = server;
        this.client = null;
        this.gui = this;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avviaBtn = new javax.swing.JButton();
        statuslbl = new javax.swing.JLabel();
        clientlbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        guiListaClient = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputlbl = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        avviaBtn.setText("Avvia Server");
        avviaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avviaBtnActionPerformed(evt);
            }
        });

        statuslbl.setText("SERVER OFFLINE");

        clientlbl.setText("                        ");

        guiListaClient.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        guiListaClient.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                guiListaClientValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(guiListaClient);

        jButton1.setText("Invia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        outputlbl.setColumns(20);
        outputlbl.setRows(5);
        jScrollPane2.setViewportView(outputlbl);

        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clientlbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statuslbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avviaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(8, 8, 8))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statuslbl)
                    .addComponent(avviaBtn)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avviaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avviaBtnActionPerformed
        if (server.avviato) {
            this.avviaBtn.setText("Start Server");
            server.chiudiServer();
        } else {
            this.avviaBtn.setText("Stop Server");
            new Thread() {
                @Override
                public void run() {
                    server.avviaServer();
                }
            }.start();
        }
    }//GEN-LAST:event_avviaBtnActionPerformed

    private void guiListaClientValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_guiListaClientValueChanged
        this.client = (InetAddress) this.guiListaClient.getSelectedValue();
    }//GEN-LAST:event_guiListaClientValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setOutputStatus(jTextField1.getText() + " @" + client.toString().split("/")[1]);
        server.send(client, jTextField1.getText());
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            if (SystemTray.isSupported()) {
                // get the SystemTray instance
                SystemTray tray = SystemTray.getSystemTray();
                // load an image
                Image image = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Federico\\Documents\\TestApp\\app\\src\\main\\res\\drawable-mdpi\\ic_launcher.png");
                
                // create a popup menu
                PopupMenu popup = new PopupMenu();
                
                MenuItem mostraItem = new MenuItem("Show");
                ActionListener mostraListener = (ActionEvent e) -> {
                    tray.remove(trayIcon);
                    gui.setVisible(true);
                };
                mostraItem.addActionListener(mostraListener);
                popup.add(mostraItem);
                /// ... add other items
                
                // construct a TrayIcon
                trayIcon = new TrayIcon(image, "Server", popup);
                // set the TrayIcon properties
                // trayIcon.addActionListener(mostraListener);
                // ...
                
                // add the tray image
                try {
                    tray.add(trayIcon);
                    this.setVisible(false);
                } catch (AWTException e) {
                    System.err.println(e);
                }
                // ...
            } else {
                // disable tray option in your application or perform other 
                // actions
                JButton btn = (JButton) evt.getSource();
                btn.setEnabled(false);
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void setServerStatus(String status) {
        statuslbl.setText(status);
    }
    
    public void setClientStatus(String status) {
        clientlbl.setText(status);
    }
    
    public void setOutputStatus(String status) {
        outputlbl.append(status + "\n");
        try {
            trayIcon.displayMessage("", status, TrayIcon.MessageType.NONE);
        } catch (NullPointerException ex) {
        }
        
    }
    
    public void updateLista(HashMap<InetAddress, Socket> lista) {
        this.guiListaClient.setListData(lista.keySet().toArray());
    }
    
    private TrayIcon trayIcon;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avviaBtn;
    private javax.swing.JLabel clientlbl;
    private javax.swing.JList guiListaClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea outputlbl;
    private javax.swing.JLabel statuslbl;
    // End of variables declaration//GEN-END:variables
}
